platform:
    - x64
    - x86

environment:
    matrix:
        - TOOLCHAIN: msvc10
        - TOOLCHAIN: msvc12
        - TOOLCHAIN: msvc14
		
test_script:
  - cmd: C:\projects\test-new\build\lib\Debug\x32\testapp.exe